### ISSUE TITLE
Problem with Umlauts in Locations

### ISSUE THREAD

**Issue by schniggie** [TobseF/impf-bot#27]
Using the docker version:

```
impf-bot    | Session ID: 0aadc7e2740679977b3e80c3834d2151
impf-bot    |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
impf-bot    |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
impf-bot    |   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
impf-bot    |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
impf-bot    |   at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
impf-bot    |   at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
impf-bot    |   at de.tfr.impf.page.LocationPage.submitInput(LocationPage.kt:30)
impf-bot    |   at de.tfr.impf.page.LocationPage.searchForFreeDate(LocationPage.kt:63)
impf-bot    |   at de.tfr.impf.ReportJob.searchFreeDateByCode(ReportJob.kt:83)
impf-bot    |   at de.tfr.impf.ReportJob.checkLocation(ReportJob.kt:59)
impf-bot    |   at de.tfr.impf.ReportJob.checkLocations(ReportJob.kt:35)
impf-bot    |   at de.tfr.impf.ReportJob.reportFreeSlots(ReportJob.kt:28)
impf-bot    |   at de.tfr.impf.StartKt.main(Start.kt:4)
impf-bot    |   at de.tfr.impf.StartKt.main(Start.kt)
impf-bot    | 10.05 10:15:48 ERROR ReportJob - Failed to check location: 74613 ?hringen
impf-bot    | element not interactable: element has zero size
impf-bot    |   (Session info: chrome=90.0.4430.93)
```

```
~/impf-bot$ cat config.properties | grep loca
# Comma separated list of locations.
locations = 71636 Ludwigsburg,74081 Heilbronn,74360 Ilsfeld-Auenstein,74549 Wolpertshausen,70174 Stuttgart,70376 Stuttgart,70629 Leinfelden-Echterdingen,71334 Waiblingen,74585 Rot am See,74613 Öhringen,74821 Mosbach,74889 Sinsheim,75056 Sulzfeld
```

**Comment by ncface** [comment]
Did you set file-encoding to UTF-8 when saving the config.properties?

Maybe these settings in DOCKERFILE do help:

\# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

**Comment by beastyrabbit** [comment]
Hi I got the same Problem running without Docker.

**Comment by schniggie** [comment]
The file-encoding is fine:

```
rancher@rancheros:~/impf-bot$ file config.properties
config.properties: UTF-8 Unicode text, with very long lines
```

But your suggestion fails:

```
Step 29/35 : RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
 ---> Running in bcca72ac3143
sed: can't read /etc/locale.gen: No such file or directory
The command '/bin/sh -c sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen' returned a non-zero code: 2
rancher@rancheros:~/impf-bot$
```

The final solution:

```
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

Will test it for some runs and then submit a PR.

**Comment by Pfuenzle** [comment]
I'm currently not at Home, so I'm unable to test it, 
but I think it would be better if this is going to get fixed in the bot itself if it is also happening there

**Comment by madrhr** [comment]
Just remove the location names, the zip code is enough to find the according location in the list
