### ISSUE TITLE
CookieNagComponent funktioniert nicht wie gewünscht?

### ISSUE THREAD

**Issue by prok42** [TobseF/impf-bot#32]
Hi,

habe mir das Projekt gestern abend auf Stand Commit 3ac48d4c4a0a7f7645dfe483f028dfdf354bb6e6 gepullt und auf einer Windows 10 Maschine mit JDK 16, Gradle 7.01, Chrome 90 und passendem chromedriver eingerichtet.
Leider scheitert der Bot schon initial auf der Startseite von "impfterminservice.de/ipftermine", da er das gewünschte Impfzentrum nicht auswählen kann, weil es vom CookieBanner überdeckt wird (liegt möglicherweise an meiner Auflösung, bei höherer Auflösung wird das Dropdown vmtl nicht überdeckt).

Ich dachte erst, dass der Bot sich gar nicht um Cookies kümmert, habe dann aber die CookieNagComponent gefunden, die, soweit ich das ohne Kotlin Kenntnisse beurteilen kann, das richtige tun sollte (der Button für die Cookies heißt nach wie vor "Auswahl bestätigen"), allerdings ist diese Bestätigung für *jeden* der Impfserver 001, 002, 003 zu machen.

**Workaround** ist: Schnell manuell klicken und dann den Bot laufen lassen.

Ich kann Dir leider keinen Merge Request anbieten (habe leider keinen Dunst von Kotlin) - wäre es möglich, auf der Startseite gleich auf das Cookiebanner zu prüfen?

**Comment by prok42** [comment]
Fehlermeldung:

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MASCHINE', ip: '192.168.2.121', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.212, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: C:\Users\User\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57868}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ee3d5ceee5255a807250e6ca44e9da3d
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
        at de.tfr.impf.page.MainPage.chooseLocation(MainPage.kt:28)
        at de.tfr.impf.ReportJob.checkLocation(ReportJob.kt:48)
        at de.tfr.impf.ReportJob.checkLocations(ReportJob.kt:35)
        at de.tfr.impf.ReportJob.reportFreeSlots(ReportJob.kt:28)
        at de.tfr.impf.StartKt.main(Start.kt:4)
        at de.tfr.impf.StartKt.main(Start.kt)
12.05 08:46:36 ERROR ReportJob - Failed to check location: 68163 Mannheim
element click intercepted: Element <span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-1vbd-container">...</span> is not clickable at point (395, 448). Other element would receive the click: <div _ngcontent-nfa-c38="" class="col-10 offset-1">...</div>
  (Session info: chrome=90.0.4430.212)

**Comment by Pfuenzle** [comment]
Ist mir beim erstellen des Dockercontainers auch aufgefallen, der Bot funktioniert nur mit 1920x1080 (oder höher), da sonst das Cookiebanner verdeckt wird

**Comment by jahill92** [comment]
In das Problem bin ich auch gelaufen:
Die Cookies werden in der funktion checkLocation erst nach       mainPage.chooseLocation(location.name) akzeptiert.
Zieh den acceptCookies() aufruf davor dann passt es.
searchFreeDateByCode hat ein ähnliches Problem. Hier muss ein acceptCookies() vor             locationPage.enterCodeSegment0(code). Vorher mit val cookieNag = CookieNagComponent(driver) das objekt erstellen.

Ich submitte später ein PR dazu

**Comment by TobseF** [comment]
Dank @jahill92 sollte dass nun hiermit behoben sein: https://github.com/TobseF/impf-bot/commit/bebd1bd8bc843e3a41f48b6af6eed87a6f3321d0
