### ISSUE TITLE
Gradle run error

### ISSUE THREAD

**Issue by lucaleicht** [TobseF/impf-bot#36]
Hi, 
i spend almost the whole night searching for the solution, reinstalled java, etc, but I still get this error with gradle run. Do you have an idea what to do?

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by c0rrre** [comment]
Hi,
Could u post the logfile?
Please check the path to the chromedriver, that fixed it for me. Remember to use "/" in the path instead of "\"

**Comment by lucaleicht** [comment]
> 
> 
> Hi,
> Could u post the logfile?
> Please check the path to the chromedriver, that fixed it for me. Remember to use "/" in the path instead of ""

I Used the "/" in the path, as shown in the other issue. 

This log is shown: BUILD SUCCESSFUL in 7s
11 actionable tasks: 11 up-to-date
PS C:\Users\lucal\Desktop\impf-bot-master> gradle run

> Task :run
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 38409
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
**Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Failed to create Chrome process.**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXXX', ip: '192.168.178.333', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
        Ordinal0 [0x0105C013+2474003]
        Ordinal0 [0x00FF29C1+2042305]
        Ordinal0 [0x00F02F68+1060712]
        Ordinal0 [0x00F1D9C8+1169864]
        Ordinal0 [0x00F1AA83+1157763]
        Ordinal0 [0x00F4A2A2+1352354]
        Ordinal0 [0x00F48FAA+1347498]
        Ordinal0 [0x00F466DB+1337051]
        Ordinal0 [0x00F23427+1192999]
        Ordinal0 [0x00F242EE+1196782]
        Ordinal0 [0x00F24279+1196665]
        GetHandleVerifier [0x011E96FC+1590332]
        GetHandleVerifier [0x01298614+2306900]
        GetHandleVerifier [0x010E9E93+543699]
        GetHandleVerifier [0x010E92CE+540686]
        Ordinal0 [0x00FF86BA+2066106]
        Ordinal0 [0x00FFD1C8+2085320]
        Ordinal0 [0x00FFD308+2085640]
        Ordinal0 [0x010067F3+2123763]
        BaseThreadInitThunk [0x77B3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77D87A4E+286]
        RtlGetAppContainerNamedObjectPath [0x77D87A1E+238]

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
        at de.tfr.impf.selenium.DriverFactoryKt.createDriver(DriverFactory.kt:15)
        at de.tfr.impf.ReportJob.<init>(ReportJob.kt:16)
        at de.tfr.impf.StartKt.main(Start.kt:4)
        at de.tfr.impf.StartKt.main(Start.kt)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by prok42** [comment]
org.openqa.selenium.WebDriverException: unknown error: Failed to create Chrome process

Das sagt ja, dass er deinen Chrome nicht starten kann - kann also sein, dass das ein Rechteproblem ist, oder er den Browser nicht findet. Welche Chrome-Version nutzt du denn und wo ist er installiert?

**Comment by lucaleicht** [comment]
> 
> 
> org.openqa.selenium.WebDriverException: unknown error: Failed to create Chrome process
> 
> Das sagt ja, dass er deinen Chrome nicht starten kann - kann also sein, dass das ein Rechteproblem ist, oder er den Browser nicht findet. Welche Chrome-Version nutzt du denn und wo ist er installiert?

Ja, so habe ich das auch verstanden. allerdings verstehe ich nicht, wieso. Die  chrome.exe liegt hier: C:\Program Files\Google\Chrome\Application
Version 90.0.4430.212 (Offizieller Build) (64-Bit)

Habe ich da etwas übersehen?

**Comment by prok42** [comment]
Hmm - da fällt mir auf die schnelle auch nix auf / ein.

Hast du mal das hier ausprobiert? (info/debug/scan) 

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by lucaleicht** [comment]
Ja, daraus werde ich aber auch nicht schlau. Was hättest du denn gern? dann lass ich es eben nochmal laufen....

**Comment by lucaleicht** [comment]
Unter info wird klar, dass er das das Java nicht geladen bekommt. ich verstehe aber nicht wie ich das ändern kann.

C:\Users\lucal\Desktop\impf-bot-master>gradle run --info
Initialized native services in: C:\Users\lucal\.gradle\native
The client will now receive all logging from the daemon (pid: 12192). The daemon log file: C:\Users\lucal\.gradle\daemon\7.0.1\daemon-12192.out.log
Starting 5th build in daemon [uptime: 36 mins 1.609 secs, performance: 100%, non-heap usage: 27% of 256 MiB]
Using 4 worker leases.
Now considering [C:\Users\lucal\Desktop\impf-bot-master] as hierarchies to watch
Watching the file system is enabled if available
Starting Build
Settings evaluated using settings file 'C:\Users\lucal\Desktop\impf-bot-master\settings.gradle.kts'.
Projects loaded. Root project using build file 'C:\Users\lucal\Desktop\impf-bot-master\build.gradle.kts'.
Included projects: [root project 'impf-bot']

> Configure project :
Evaluating root project 'impf-bot' using build file 'C:\Users\lucal\Desktop\impf-bot-master\build.gradle.kts'.
kotlin scripting plugin: created the scripting discovery configuration: kotlinScriptDef
kotlin scripting plugin: created the scripting discovery configuration: testKotlinScriptDef
Caching disabled for Kotlin DSL accessors for root project 'impf-bot' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for root project 'impf-bot' as it is up-to-date.
All projects evaluated.
Selected primary task 'run' from project :
Tasks to be executed: [task ':compileKotlin', task ':compileJava', task ':processResources', task ':classes', task ':run']
Tasks that were excluded: []
:compileKotlin (Thread[Execution worker for ':',5,main]) started.

> Task :compileKotlin UP-TO-DATE
Caching disabled for task ':compileKotlin' because:
  Build cache is disabled
Skipping task ':compileKotlin' as it is up-to-date.
:compileKotlin (Thread[Execution worker for ':',5,main]) completed. Took 0.085 secs.
:compileJava (Thread[Execution worker for ':',5,main]) started.

**> Task :compileJava NO-SOURCE**
file or directory 'C:\Users\lucal\Desktop\impf-bot-master\src\main\java', not found
Skipping task ':compileJava' as it has no source files and no previous output files.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:processResources (Thread[Execution worker for ':' Thread 3,5,main]) started.**

> Task :processResources UP-TO-DATE
Caching disabled for task ':processResources' because:
  Build cache is disabled
Skipping task ':processResources' as it is up-to-date.
:processResources (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.003 secs.
:classes (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
:run (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :run
Caching disabled for task ':run' because:
  Build cache is disabled
Task ':run' is not up-to-date because:
  **Task has not declared any outputs despite executing actions.
Starting process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe''. Working directory: C:\Users\lucal\Desktop\impf-bot-master Command: C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe** -Dfile.encoding=windows-1252 -Duser.country=DE -Duser.language=de -Duser.variant -cp C:\Users\lucal\Desktop\impf-bot-master\build\classes\java\main;C:\Users\lucal\Desktop\impf-bot-master\build\classes\kotlin\main;C:\Users\lucal\Desktop\impf-bot-master\build\resources\main;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.github.elbekD\kt-telegram-bot\1.3.8\c0122d33948b40ff6f426dc8014637c9a38d4b39\kt-telegram-bot-1.3.8.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.4.32\3302f9ec8a5c1ed220781dbd37770072549bd333\kotlin-stdlib-jdk8-1.4.32.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-java\3.141.59\e8e20b741299cb8ffedbd2925a3ab69d08b41063\selenium-java-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-support\3.141.59\8735de5049acf0e761defc65ee5837d6541abaf5\selenium-support-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\io.github.microutils\kotlin-logging-jvm\2.0.6\539f788429038f058f9c0da3cac14f7b653f0db8\kotlin-logging-jvm-2.0.6.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.slack.api\slack-api-client\1.7.1\4ef9e4100115805f02e0133f8e86f55ad2b90458\slack-api-client-1.7.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-simple\1.7.30\e606eac955f55ecf1d8edcccba04eb8ac98088dd\slf4j-simple-1.7.30.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.4.32\3546900a3ebff0c43f31190baf87a9220e37b7ea\kotlin-stdlib-jdk7-1.4.32.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-chrome-driver\3.141.59\67137314736c6a2f39a8aa59a562e9616ae5f77e\selenium-chrome-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-edge-driver\3.141.59\fc09c66f2d0b33b0816d770761ad1d599ef0df29\selenium-edge-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-firefox-driver\3.141.59\a99f2fe2a42747ed9809d4f62f51a9e1b336dde8\selenium-firefox-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-ie-driver\3.141.59\677b9b414a3a9bb2aeea89042a7b326edeb13a82\selenium-ie-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-opera-driver\3.141.59\6b11ed01182bfd8bb62ddeae34cf9eadd3cfc7ff\selenium-opera-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-safari-driver\3.141.59\a32b5b88f46ea4b0356079f0d2e2217543923046\selenium-safari-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-remote-driver\3.141.59\1c79ca890c312ff9916bd95df4f0c5182ec722d8\selenium-remote-driver-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.9.1\51215279c3fe472c59b6b7dd7491e6ac2e28a81b\okhttp-4.9.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core\1.0.1\f33e8dab753f33d1bbb07cca664fd6f13d993d7e\kotlinx-coroutines-core-1.0.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\2.8.0\49b64e09d81c0cc84b267edd0c2fd7df5a64c78c\okio-jvm-2.8.0.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.4.32\461367948840adbb0839c51d91ed74ef4a9ccb52\kotlin-stdlib-1.4.32.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-api\3.141.59\e006ffd3aa7841e6e9125d9e6691b3a6b7592b05\selenium-api-3.141.59.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\net.bytebuddy\byte-buddy\1.8.15\cb36fe3c70ead5fcd016856a7efff908402d86b8\byte-buddy-1.8.15.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-exec\1.3\8dfb9facd0830a27b1b5f29f84593f0aeee7773b\commons-exec-1.3.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\25.0-jre\7319c34fa5866a85b6bad445adad69d402323129\guava-25.0-jre.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.30\b5a4b6d16ab13e34a88fae84c35cd5d68cac922c\slf4j-api-1.7.30.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core-common\1.0.1\679991d1b388fd9392eeb3d63b10b3f4c284f389\kotlinx-coroutines-core-common-1.0.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.4.32\ef50bfa2c0491a11dcc35d9822edbfd6170e1ea2\kotlin-stdlib-common-1.4.32.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.slack.api\slack-api-model\1.7.1\df3e5491736cb20e984b68dc37674d3fe35e08b9\slack-api-model-1.7.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.6\9180733b7df8542621dc12e21e87557e8c99b8cb\gson-2.8.6.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-servlet\9.4.25.v20191220\bee77d6a4f87dc90d5bc142cbd6cef470ec46aae\jetty-servlet-9.4.25.v20191220.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-security\9.4.25.v20191220\593ff5b5dfd5bf973184329f5d1209b9a411ec12\jetty-security-9.4.25.v20191220.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-server\9.4.25.v20191220\5b352c9f9135a1c20e4808e5cb1d84fbddfdc460\jetty-server-9.4.25.v20191220.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\1.3.9\40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf\jsr305-1.3.9.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-compat-qual\2.0.0\fc89b03860d11d6213d0154a62bcd1c2f69b9efa\checker-compat-qual-2.0.0.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.google.errorprone\error_prone_annotations\2.1.3\39b109f2cd352b2d71b52a3b5a1a9850e1dc304b\error_prone_annotations-2.1.3.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\com.google.j2objc\j2objc-annotations\1.1\ed28ded51a8b1c6b112568def5f4b455e6809019\j2objc-annotations-1.1.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.codehaus.mojo\animal-sniffer-annotations\1.14\775b7e22fb10026eed3f86e8dc556dfafe35f2d5\animal-sniffer-annotations-1.14.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\javax.servlet\javax.servlet-api\3.1.0\3cd63d075497751784b2fa84be59432f4905bf7c\javax.servlet-api-3.1.0.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-http\9.4.25.v20191220\c3aa7da362f1a492667ce754ba16b2535b793668\jetty-http-9.4.25.v20191220.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-io\9.4.25.v20191220\3eb34b5481012701de0ea9dfaf2bdf1dbb947b16\jetty-io-9.4.25.v20191220.jar;C:\Users\lucal\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-util\9.4.25.v20191220\fd8b642cc16728f1c36ca6a64653cb1b26ec0232\jetty-util-9.4.25.v20191220.jar de.tfr.impf.StartKt
Successfully started process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe''
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 3911
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Failed to create Chrome process.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LUCA-PC', ip: '192.168.178.xxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
        Ordinal0 [0x007AC013+2474003]
        Ordinal0 [0x007429C1+2042305]
        Ordinal0 [0x00652F68+1060712]
        Ordinal0 [0x0066D9C8+1169864]
        Ordinal0 [0x0066AA83+1157763]
        Ordinal0 [0x0069A2A2+1352354]
        Ordinal0 [0x00698FAA+1347498]
        Ordinal0 [0x006966DB+1337051]
        Ordinal0 [0x00673427+1192999]
        Ordinal0 [0x006742EE+1196782]
        Ordinal0 [0x00674279+1196665]
        GetHandleVerifier [0x009396FC+1590332]
        GetHandleVerifier [0x009E8614+2306900]
        GetHandleVerifier [0x00839E93+543699]
        GetHandleVerifier [0x008392CE+540686]
        Ordinal0 [0x007486BA+2066106]
        Ordinal0 [0x0074D1C8+2085320]
        Ordinal0 [0x0074D308+2085640]
        Ordinal0 [0x007567F3+2123763]
        BaseThreadInitThunk [0x76D8FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77677A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77677A4E+238]

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
        at de.tfr.impf.selenium.DriverFactoryKt.createDriver(DriverFactory.kt:15)
        at de.tfr.impf.ReportJob.<init>(ReportJob.kt:16)
        at de.tfr.impf.StartKt.main(Start.kt:4)
        at de.tfr.impf.StartKt.main(Start.kt)

> Task :run FAILED
:run (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 2.983 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 1 executed, 2 up-to-date
Watched directory hierarchies: [C:\Users\lucal\Desktop\impf-bot-master]

**Comment by prok42** [comment]
Hmm bei adopt gibt es ja Hotspot und die openJ9 vm, vielleicht liegt es an der Hotspot Version?

Ansonsten: probier doch mal das "java.com" jdk 16 von oracle, damit läuft es bei mir

**Comment by lucaleicht** [comment]
> Hmm bei adopt gibt es ja Hotspot und die openJ9 vm, vielleicht liegt es an der Hotspot Version?
> 
> 
> 
> Ansonsten: probier doch mal das "java.com" jdk 16 von oracle, damit läuft es bei mir 

Leider hat das auch nicht geholfen. Ich bin immernoch auf der Suche. Bald verbringe ich mehr Zeit damit als die nervige Seite von Hand zu aktualisieren. 

Falls jemand noch einen Tipp hat, gern her damit.

**Comment by Pfuenzle** [comment]
Denke das einfachste wäre, Docker zu installieren und den Dockercontainer zu nutzen. Wenn sogar die offizielle Java-Version nicht funktioniert, wüsste ich auch nicht mehr

**Comment by lucaleicht** [comment]
Das vermute ich auch. Dann werde ich mich da mal dran wagen.

**Comment by danieldaeschle** [comment]
Ich habe das gleiche Problem in meinem Docker container

**Comment by danieldaeschle** [comment]
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 90.0.4430.212 with binary path /usr/bin/chromium
```

**Comment by danieldaeschle** [comment]
Das hat es behoben für mich
```
diff --git a/Dockerfile b/Dockerfile
index 0668993..339db84 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,10 +2,13 @@ FROM debian:buster
 
 # install apt dependencies
 RUN apt-get update -y
-RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip wget git default-jdk chromium=90.0.4430.212-1~deb10u1 xorg vnc4server autocutsel lxde-core novnc python-websockify 
+RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip wget git default-jdk xorg vnc4server autocutsel lxde-core novnc python-websockify 
 
 WORKDIR /app
 
+RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+RUN DEBIAN_FRONTEND=noninteractive apt-get install ./google-chrome-stable_current_amd64.deb -y
+
 # download gradle
 RUN wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip  -P /tmp/ && \
     unzip -d /opt/gradle /tmp/gradle-7.0.2-bin.zip && \

```
