### ISSUE TITLE
Exception in stacktrace (value=//input[@formcontrolname='age')

### ISSUE THREAD

**Issue by oldgitdaddy** [TobseF/impf-bot#49]
Hi, I have the following exception in the stacktrace. I am a bit concerned, that the bot does not handle age properly. Any idea, how to fix?
```
 Element info: {Using=xpath, value=//input[@formcontrolname='age']}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
        at de.tfr.impf.page.AbstractPage.findBy(AbstractPage.kt:19)
        at de.tfr.impf.page.LocationPage.enterAge(LocationPage.kt:44)
        at de.tfr.impf.ReportJob.checkClaim(ReportJob.kt:124)
        at de.tfr.impf.ReportJob.checkLocation(ReportJob.kt:70)
        at de.tfr.impf.ReportJob.checkLocations(ReportJob.kt:44)
        at de.tfr.impf.ReportJob.reportFreeSlots(ReportJob.kt:37)
        at de.tfr.impf.StartKt.main(Start.kt:4)
        at de.tfr.impf.StartKt.main(Start.kt)
```

**Comment by miwurster** [comment]
Same here. Any hint how to fix this?

I used the latest master to build the Docker image.

**Comment by Pfuenzle** [comment]
Do you see anything unusual in the browser window via VNC?

**Comment by miwurster** [comment]
I couldn't catch the moment in VNC when the error is popping up. I'll monitor it and come back to you.

**Comment by miwurster** [comment]
Atm I assume it belongs to my "aggressive" timings ;-) 

I use the following timings now and it seems to work as intended:
```
# Waiting time before checking the next location in seconds [s]
# waitingTime = 120
waitingTime = 10
# Waiting time for a manual user interaction in minutes [m]
waitingTimeForUserAction = 15
# Waiting time in Waiting Room in minutes [m]
waitingTimeInWaitingRoom = 15
# Timeout when searching an element on the page in seconds [s]
searchElementTimeout = 16
# Explicit waiting time for browser updates in seconds [s]
waitingTimeForBrowser = 2
```

Anyone can share some best practice settings concerning the timeouts?
