### ISSUE TITLE
Gradle-Run-Error

### ISSUE THREAD

**Issue by PadPlay** [TobseF/impf-bot#8]
Recently got this error. Is there any way of fixing it? Thanks in advance.

![grafik](https://user-images.githubusercontent.com/68967110/116907840-6ce99b00-ac42-11eb-9524-870073cdb31a.png)

**Comment by TobseF** [comment]
I pushed an updated version with support for Gradle 7.0. This was possible because of the new [shadow plugin](https://github.com/johnrengelman/shadow) release. Check it out.

Anyway, during setup, the `gradlew` script should install the Gradle version which is configured in the `gradle-wrapper.properties`. If you have another version installed than
```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-all.zip
```
delete the `.gradle` folder and run the `gradlew` script again.

**Comment by superflo22** [comment]
Im using Gradle 7.0 and Unix.
Getting the same error:
`Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
        at de.tfr.impf.selenium.DriverFactoryKt.createDriver(DriverFactory.kt:11)
        at de.tfr.impf.ReportJob.<init>(ReportJob.kt:14)
        at de.tfr.impf.StartKt.main(Start.kt:4)
        at de.tfr.impf.StartKt.main(Start.kt)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:18364/status] to be available after 20001 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
        ... 12 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 13 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk/bin/java'' finished with non-zero exit value 1`
The Chrome window opens but the Driver times out somehow

**Comment by superflo22** [comment]
Turns out switching from Chrome to Chromium will solve the time out. Somehow Chrome crashed because of some VAAPI libary (ERROR:vaapi_wrapper.cc(1067)).
